// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yulueuhBIILhm6A88BfIsWOXgOBoa28',
    appId: '1:329166780630:web:dfbcafa322e5381255b177',
    messagingSenderId: '329166780630',
    projectId: 'city-student-portal',
    authDomain: 'city-student-portal.firebaseapp.com',
    storageBucket: 'city-student-portal.firebasestorage.app',
    measurementId: 'G-GF3W3PK5PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCagD6y-sXDmIls3o7POrNIrOSz8Zn_TWs',
    appId: '1:329166780630:android:02c266422ffdbf1255b177',
    messagingSenderId: '329166780630',
    projectId: 'city-student-portal',
    storageBucket: 'city-student-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3013pReRkhaKN5WkVgvEmNepriq3EuYc',
    appId: '1:329166780630:ios:95a671483c40323555b177',
    messagingSenderId: '329166780630',
    projectId: 'city-student-portal',
    storageBucket: 'city-student-portal.firebasestorage.app',
    iosBundleId: 'com.example.studentPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3013pReRkhaKN5WkVgvEmNepriq3EuYc',
    appId: '1:329166780630:ios:95a671483c40323555b177',
    messagingSenderId: '329166780630',
    projectId: 'city-student-portal',
    storageBucket: 'city-student-portal.firebasestorage.app',
    iosBundleId: 'com.example.studentPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5yulueuhBIILhm6A88BfIsWOXgOBoa28',
    appId: '1:329166780630:web:a8066ed0123e53e755b177',
    messagingSenderId: '329166780630',
    projectId: 'city-student-portal',
    authDomain: 'city-student-portal.firebaseapp.com',
    storageBucket: 'city-student-portal.firebasestorage.app',
    measurementId: 'G-MEBG3XZ54S',
  );
}
