import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'login_page.dart';
import 'dashboard_page.dart';
import 'pages/fees_block_page.dart';
import 'signup_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const StudentPortalApp());
}

class StudentPortalApp extends StatelessWidget {
  const StudentPortalApp({super.key});

  // Colour palette
  static const Color lightRed = Color.fromARGB(255, 211, 32, 15);
  static const Color background = Colors.white;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'City University Student Portal',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: background,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color.fromARGB(255, 224, 31, 13),
          surface: background,
          brightness: Brightness.light,
        ),
        appBarTheme: const AppBarTheme(elevation: 0, centerTitle: true),
        useMaterial3: true,
      ),
      home: const LoginPage(), // first screen

      routes: {
        '/dashboard': (_) => const DashboardPage(),
        '/blocked': (_) => const FeesBlockPage(),
        '/signup': (_) => const SignupPage(), // add this line
        '/admin': (_) => const DashboardPage(),
      },
    );
  }
}
